name: experiment      # experiment name
task: multi           # choose btw text, audio, video or multi
save_experiment: true # save experiment
logs: logs            # logs path

load:                 # data to use (only for multi)
  text: [true, logs/text_5]
  audio: [true, logs/audio_3]
  video: [false, null]

data:
  path: data          # data path
  sequence_size: 20   # num word in sequence
  num_frames: 10      # num frames by speaker
  audio_length: 2000  # num milisecondes by speaker
  num_features: 709   # num landmarks in the frames
  num_classes: 2      # num classes

model:
  text:
    pretrained_model_name: camembert-base
    hidden_size: 64
  
  audio:
    pretrained_model_name: facebook/wav2vec2-large-960h
  
  video:
    hidden_size: 100
  
  multi:
    likelihood: false
    hidden_size: 128
    freeze_basemodel: true
  
learning:
  learning_rate: 0.001        # learning rate
  batch_size: 128             # batch size
  epochs: 2                   # number of epochs
  device: cuda                # choose between cuda or cpu
  milesstone: [5, 15]         # gradient decay at epoch 5 and 15
  gamma: 0.1                  # learning rate will be multiplicate by 0.1 at epochs 5 and 15
  loss: crossentropy          # loss function
  save_learning_curves: false # save learning curves
  
metrics:
  acc: true         # accuracy
  precision: true   # precision
  recall: true      # recall
  f1: true          # f1 score

