name: experiment
task: video           # choose btw text, audio, video or all
save_experiment: true
logs: logs

data:
  path: /content/gdrive/MyDrive/SAM_I3A/data          # data path
  sequence_size: 20   # num word in sequence
  num_frames: 10      # num frames by speaker
  audio_length: 1000  # num milisecondes by speaker
  num_features: 709   # num landmars in the frames
  num_classes: 2      # num classes

model:
  text:
    pretrained_model_name: camembert-base
    hidden_size: 768
  
  audio:
    pretrained_model_name: facebook/wav2vec2-large-960h
  
  video:
    hidden_size: 100
  
  all:
    hidden_size: 100
  
learning:
  learning_rate: 0.01
  batch_size: 16
  epochs: 30
  device: cuda
  milesstone: [5, 15]         # gradient decay at epoch 5 and 15
  gamma: 0.1                  # learning rate will be multiplicate by 0.1 at epochs 5 and 15
  loss: crossentropy
  save_learning_curves: true
  
metrics:
  acc: true
  precision: true
  recall: true
  f1: true

